/** 12 cuốn sách khởi tạo. category dùng enum gạch dưới khớp Prisma. */
const ol = (id: number) => `https://covers.openlibrary.org/b/id/${id}-L.jpg?default=false`;

export const BOOKS_SEED = [
  { title: 'Đại Dương Đen', author: 'Đặng Hoàng Giang', category: 'tram_cam', rating: 5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#3d4e40,#1f2a26)', coverUrl: ol(13338223),
    excerpt: 'Hành trình thấu hiểu người trầm cảm tại Việt Nam — giúp bạn và người thân bớt cô đơn, bớt phán xét.',
    detail: '"Đại Dương Đen" là tập hợp những câu chuyện có thật về người trầm cảm tại Việt Nam, được Đặng Hoàng Giang ghi lại bằng sự thấu cảm sâu sắc. Cuốn sách giúp người đọc hiểu trầm cảm không phải là "yếu đuối" hay "làm quá", mà là một căn bệnh thực sự cần được lắng nghe và chăm sóc.',
    whyRead: 'Nếu bạn hoặc người thân đang trải qua trầm cảm, cuốn sách này giúp bạn cảm thấy được thấu hiểu và bớt cô đơn hơn.' },
  { title: 'Đi Tìm Lẽ Sống', author: 'Viktor E. Frankl', category: 'y_nghia', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#5f7a63,#3d4e40)', coverUrl: ol(11203708),
    excerpt: 'Tìm thấy ý nghĩa ngay cả trong đau khổ tột cùng — một chỗ dựa tinh thần sâu sắc.',
    detail: 'Viktor Frankl — bác sĩ tâm thần sống sót qua trại tập trung Đức Quốc Xã — chia sẻ cách con người có thể tìm thấy ý nghĩa để sống ngay cả trong hoàn cảnh khắc nghiệt nhất. Đây là nền tảng của liệu pháp ý nghĩa (logotherapy).',
    whyRead: 'Khi bạn cảm thấy cuộc sống mất phương hướng, cuốn sách này giúp bạn tìm lại lý do để tiếp tục.' },
  { title: 'Bước Chậm Lại Giữa Thế Gian Vội Vã', author: 'Hae Min', category: 'chua_lanh', rating: 5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#6f6a5d,#403d36)', coverUrl: ol(12217703),
    excerpt: 'Những lời nhắn dịu dàng để bạn dừng lại, thở, và tử tế hơn với chính mình.',
    detail: 'Thiền sư Hae Min viết những lời nhắn ngắn gọn, dịu dàng về tình yêu, mối quan hệ, và sự nghỉ ngơi. Mỗi trang là một khoảng lặng giúp người đọc chậm lại giữa cuộc sống vội vã.',
    whyRead: 'Phù hợp để đọc mỗi ngày một chút khi bạn cảm thấy quá tải và cần được vỗ về.' },
  { title: 'Sức Mạnh Của Hiện Tại', author: 'Eckhart Tolle', category: 'chanh_niem', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#4b614f,#2a342c)', coverUrl: ol(2401616),
    excerpt: 'Học cách buông những lo lắng về quá khứ và tương lai, an trú trong khoảnh khắc hiện tại.',
    detail: 'Eckhart Tolle hướng dẫn cách thoát khỏi vòng xoáy suy nghĩ tiêu cực bằng việc sống trọn vẹn trong hiện tại. Một cuốn sách nền tảng về chánh niệm và tỉnh thức.',
    whyRead: 'Nếu tâm trí bạn hay lo lắng về tương lai hoặc dằn vặt quá khứ, cuốn sách giúp bạn neo về hiện tại.' },
  { title: 'Khi Mây Đen Kéo Tới', author: 'Matthew Johnstone', category: 'tram_cam', rating: 5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#7f9882,#4b614f)', coverUrl: ol(8404533),
    excerpt: 'Cuốn sách tranh nhẹ nhàng giúp gọi tên và sống chung với những ngày u ám.',
    detail: 'Qua hình ảnh "chú chó đen" ẩn dụ cho trầm cảm, Matthew Johnstone giúp người đọc hình dung và nói về căn bệnh này một cách nhẹ nhàng, không đáng sợ.',
    whyRead: 'Dễ đọc, ít chữ — phù hợp khi bạn không đủ năng lượng cho những cuốn sách dày.' },
  { title: 'Thói Quen Nguyên Tử', author: 'James Clear', category: 'thoi_quen', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#8c8676,#5a564b)', coverUrl: ol(12539702),
    excerpt: 'Xây những thói quen nhỏ, tích cực để dần ổn định lại nhịp sống và tâm trạng.',
    detail: 'James Clear chỉ ra cách những thay đổi nhỏ 1% mỗi ngày tạo nên khác biệt lớn theo thời gian. Một cẩm nang thực tế để xây thói quen lành mạnh.',
    whyRead: 'Khi bạn muốn ổn định lại nhịp sống bằng những bước nhỏ, dễ thực hiện.' },
  { title: 'Người Không Hoàn Hảo', author: 'Brené Brown', category: 'chua_lanh', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#a9bbab,#5f7a63)', coverUrl: ol(7237826),
    excerpt: 'Khám phá sức mạnh của sự dễ tổn thương và cách nó giúp chúng ta sống trọn vẹn hơn.',
    detail: 'Brené Brown — nhà nghiên cứu về sự tổn thương và lòng can đảm — chỉ ra rằng chấp nhận sự không hoàn hảo của bản thân là chìa khóa để sống chân thật và hạnh phúc.',
    whyRead: 'Nếu bạn hay tự phê phán mình quá khắt khe, cuốn sách giúp bạn tử tế hơn với chính mình.' },
  { title: 'Đừng Lo Về Những Điều Nhỏ Nhặt', author: 'Richard Carlson', category: 'lo_au', rating: 4, reviewedByExpert: false,
    coverGradient: 'linear-gradient(150deg,#b5573c,#7f3a2a)', coverUrl: ol(546371),
    excerpt: '100 bài học ngắn giúp bạn nhìn cuộc sống với đôi mắt bình thản hơn.',
    whyRead: 'Mỗi bài chỉ 1-2 trang, đọc lúc nào cũng được khi bạn cần một lời nhắc bình tâm.' },
  { title: 'Lo Âu - Hiểu Để Vượt Qua', author: 'Scott Stossel', category: 'lo_au', rating: 4, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#719c80,#3d4e40)', coverUrl: ol(11683330),
    excerpt: 'Cái nhìn khoa học và đầy nhân văn về lo âu — từ nguồn gốc đến cách sống chung với nó.',
    whyRead: 'Nếu bạn muốn hiểu lo âu một cách sâu sắc, vừa khoa học vừa từ trải nghiệm thật.' },
  { title: 'Trí Tuệ Xúc Cảm', author: 'Daniel Goleman', category: 'chua_lanh', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#4d7596,#2f5c78)', coverUrl: ol(1359485),
    excerpt: 'Hiểu và điều tiết cảm xúc của mình — kỹ năng nền tảng cho sức khỏe tinh thần.',
    whyRead: 'Giúp bạn nhận diện và quản lý cảm xúc tốt hơn trong cuộc sống hằng ngày.' },
  { title: 'Quẳng Gánh Lo Đi Và Vui Sống', author: 'Dale Carnegie', category: 'lo_au', rating: 4, reviewedByExpert: false,
    coverGradient: 'linear-gradient(150deg,#c87358,#7f3a2a)', coverUrl: ol(10829208),
    excerpt: 'Những nguyên tắc thực tế giúp ngừng lo lắng và bắt đầu sống an nhiên hơn.',
    whyRead: 'Kinh điển về quản lý lo âu với nhiều ví dụ đời thường, dễ áp dụng.' },
  { title: 'Thiền Cho Người Bận Rộn', author: 'Andy Puddicombe', category: 'chanh_niem', rating: 4.5, reviewedByExpert: true,
    coverGradient: 'linear-gradient(150deg,#7f9882,#547d63)', coverUrl: ol(10209073),
    excerpt: 'Chỉ 10 phút mỗi ngày để làm dịu tâm trí — thiền không hề phức tạp như bạn nghĩ.',
    whyRead: 'Người sáng lập app Headspace hướng dẫn thiền đơn giản, hợp người mới bắt đầu.' },
];
